# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Build/Test"

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ "master" ]
  pull_request:
    paths-ignore:
      - 'README.md'
    branches: [ "master" ]

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: "go.mod"
        id: go

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Build
        run: make build

  test:
    name: "Tests"
    needs: build
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: "go.mod"

      - name: Run Test
        run: make test
